services:
  - type: web
    name: ai-chatbot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from transformers import pipeline; pipeline('text-generation', model='TinyLlama/TinyLlama-1.1B-Chat-v1.0', device_map='cpu')"
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.16"
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: "max_split_size_mb:32"
